window.appTranslations = {
    en: {
        "title_settings": "Configurations",
        "btn_new": "New",
        "lbl_profile_name": "Profile Name",
        "lbl_base_model": "Base Model",
        "lbl_creativity": "Creativity",
        "lbl_response_length": "Response Length",
        "lbl_instructions": "Instructions",
        "btn_load_context": "Load Context Documents",
        "ph_instructions": "Base instructions for this model...",
        "lbl_indexed_docs": "Indexed Documents in Knowledge Base",
        "btn_delete_profile": "Delete Profile",
        "btn_cancel": "Cancel",
        "btn_save": "Save",
        
        "chat_new": "New Chat",
        "chat_model": "Model:",
        "chat_ready": "ready",
        "chat_placeholder": "Type a message…",
        "chat_reasoning": "Reasoning effort",
        "chat_reasoning_low": "⚡ Low",
        "chat_reasoning_medium": "💡 Medium",
        "chat_reasoning_high": "🔍 High",
        "chat_preview": "Preview (Canvas)",

        "msg_loading": "Loading...",
        "msg_verifying": "Verifying...",
        "msg_downloading": "Downloading...",
        "msg_save_changes": "Save Changes",
        "msg_indexing": "✅ Indexing in background",
        "msg_error_processing": "⚠️ Error processing",
        "msg_delete_confirm": "Are you sure you want to delete this profile?",
        "msg_no_indexed": "No indexed documents.",
        "msg_error_loading": "Error loading.",
        "chat_model_title": "Select Model",
        "chat_attach": "Attach image or PDF",
        "chat_voice": "Voice dictate",
        "chat_agent_label": "Agent Mode:",
        "chat_agent_req_title": "Agent requests permission to execute:",
        "chat_agent_approve": "Approve",
        "chat_agent_always_approve": "Always approve",
        "chat_agent_reject": "Reject",
        "chat_agent_rejected_msg": "User rejected tool execution.",
        "chat_executing": "● executing tools…",
        "chat_thinking": "● thinking…",
        "chat_response_from": "response from:",
        "chat_generated_by": "⚡ Generated by",
        "chat_orchestrator": "Orchestrator",
        "tab_models": "Models",
        "tab_agents": "Agents",
        "agent_tab_title": "My Agents",
        "agent_btn_add": "+ Add",
        "agent_desc_history": "History of created agents. Select one to edit or activate it as an orchestrator.",
        "agent_msg_no_agents": "No agents created.",
        "agent_btn_back": "← Back",
        "agent_lbl_name": "Agent Name",
        "agent_ph_name": "e.g. Developer Agent",
        "agent_btn_save": "Save Agent",
        "agent_title_orch": "Orchestrator",
        "agent_desc_orch": "Select the main model that will delegate tasks to sub-agents in this configuration.",
        "agent_opt_none": "None (Agent without orchestrator)",
        "agent_title_sub": "Available Sub-Agents",
        "agent_desc_sub": "Select the profiles the orchestrator can use as tools.",
        "agent_msg_no_profiles": "No custom profiles created.",
        "agent_title_behavior": "Agentic Behavior",
        "agent_desc_behavior": "If you enabled \"automatic tool approval\" in agent mode, you can revoke it here to request manual confirmation again before executing commands or actions on your system.",
        "agent_btn_revoke": "Revoke Automatic Approval"
    },
    es: {
        "title_settings": "Configuración",
        "btn_new": "Nuevo",
        "lbl_profile_name": "Nombre de Perfil",
        "lbl_base_model": "Modelo Base",
        "lbl_creativity": "Creatividad",
        "lbl_response_length": "Largo de Respuesta",
        "lbl_instructions": "Instrucciones",
        "btn_load_context": "Cargar Contexto (Docs)",
        "ph_instructions": "Instrucciones base para este modelo...",
        "lbl_indexed_docs": "Documentos en Base de Conocimiento",
        "btn_delete_profile": "Eliminar Perfil",
        "btn_cancel": "Cancelar",
        "btn_save": "Guardar y Aplicar",

        "chat_new": "Nuevo Chat",
        "chat_model": "Modelo:",
        "chat_ready": "listo",
        "chat_placeholder": "Escribe un mensaje…",
        "chat_reasoning": "Nivel de razonamiento",
        "chat_reasoning_low": "⚡ Bajo",
        "chat_reasoning_medium": "💡 Medio",
        "chat_reasoning_high": "🔍 Alto",
        "chat_preview": "Vista Previa (Canvas)",

        "msg_loading": "Cargando...",
        "msg_verifying": "Verificando...",
        "msg_downloading": "Descargando...",
        "msg_save_changes": "Guardar Cambios",
        "msg_indexing": "✅ Indexando en segundo plano",
        "msg_error_processing": "⚠️ Error procesando",
        "msg_delete_confirm": "¿Estás seguro de que quieres eliminar este perfil?",
        "msg_no_indexed": "No hay documentos indexados.",
        "msg_error_loading": "Error al cargar.",
        "chat_model_title": "Elegir Modelo",
        "chat_attach": "Adjuntar imagen o PDF",
        "chat_voice": "Dictado por voz",
        "chat_agent_label": "Modo Agente:",
        "chat_agent_req_title": "El agente solicita permiso para ejecutar:",
        "chat_agent_approve": "Aprobar",
        "chat_agent_always_approve": "Aprobar siempre",
        "chat_agent_reject": "Rechazar",
        "chat_agent_rejected_msg": "El usuario rechazó la ejecución de la herramienta.",
        "chat_executing": "● ejecutando herramientas…",
        "chat_thinking": "● pensando…",
        "chat_response_from": "respuesta desde:",
        "chat_generated_by": "⚡ Generado por",
        "chat_orchestrator": "Orquestador",
        "tab_models": "Modelos",
        "tab_agents": "Agentes",
        "agent_tab_title": "Mis Agentes",
        "agent_btn_add": "+ Agregar",
        "agent_desc_history": "Histórico de agentes creados. Selecciona uno para editarlo o actívalo como orquestador.",
        "agent_msg_no_agents": "No hay agentes creados.",
        "agent_btn_back": "← Volver",
        "agent_lbl_name": "Nombre del Agente",
        "agent_ph_name": "Ej: Agente Programador",
        "agent_btn_save": "Guardar Agente",
        "agent_title_orch": "Orquestador",
        "agent_desc_orch": "Selecciona el modelo principal que delegará tareas a los sub-agentes en esta configuración.",
        "agent_opt_none": "Ninguno (Agente sin orquestador)",
        "agent_title_sub": "Sub-Agentes Disponibles",
        "agent_desc_sub": "Selecciona los perfiles que el orquestador podrá usar como herramientas.",
        "agent_msg_no_profiles": "No hay perfiles personalizados creados.",
        "agent_title_behavior": "Comportamiento Agéntico",
        "agent_desc_behavior": "Si habilitaste la \"aprobación automática de herramientas\" en el modo agente, puedes revocarla aquí para volver a pedir confirmación manual antes de ejecutar comandos o acciones en tu sistema.",
        "agent_btn_revoke": "Revocar Aprobación Automática"
    }
};

window.i18n = {
    currentLang: 'en',
    
    init: function() {
        this.currentLang = localStorage.getItem('appLang') || 'en';
        this.applyTranslations();

        // Listen for changes from other windows sharing same localStorage
        window.addEventListener('storage', (e) => {
            if (e.key === 'appLang') {
                this.currentLang = e.newValue;
                this.applyTranslations();
                const langSelect = document.getElementById('lang-select');
                if (langSelect && langSelect.value !== this.currentLang) {
                    langSelect.value = this.currentLang;
                }
            }
        });
        
        // Setup dropdown if exists
        const langSelect = document.getElementById('lang-select');
        if (langSelect) {
            langSelect.value = this.currentLang;
            langSelect.addEventListener('change', (e) => {
                this.currentLang = e.target.value;
                localStorage.setItem('appLang', this.currentLang);
                this.applyTranslations();
                // trigger storage event manually in case logic depends on it in same frame
                window.dispatchEvent(new Event('appLangChanged')); 
            });
        }
        
        window.addEventListener('appLangChanged', () => {
            this.currentLang = localStorage.getItem('appLang') || 'en';
            this.applyTranslations();
        });
    },

    t: function(key) {
        if (window.appTranslations[this.currentLang] && window.appTranslations[this.currentLang][key]) {
            return window.appTranslations[this.currentLang][key];
        }
        return key;
    },

    applyTranslations: function() {
        const elements = document.querySelectorAll('[data-i18n]');
        elements.forEach(el => {
            const key = el.getAttribute('data-i18n');
            const translation = this.t(key);
            
            if (el.tagName === 'INPUT' && (el.type === 'button' || el.type === 'submit')) {
                el.value = translation;
            } else if (el.tagName === 'TEXTAREA' || (el.tagName === 'INPUT' && el.type === 'text')) {
                if (el.hasAttribute('placeholder') || el.id === 'modelPrompt' || el.id === 'prompt') {
                    el.placeholder = translation;
                } else {
                    el.innerText = translation;
                }
            } else {
                // If it contains SVG/Icons, we need to replace just the text node
                let replaced = false;
                for (const node of el.childNodes) {
                    if (node.nodeType === Node.TEXT_NODE && node.nodeValue.trim().length > 0) {
                        node.nodeValue = " " + translation + " ";
                        replaced = true;
                        break;
                    }
                }
                if (!replaced) el.textContent = translation; 
            }
        });
        
        // Handle title translations explicitly to avoid overwriting SVG inner contents
        const titleElements = document.querySelectorAll('[data-i18n-title]');
        titleElements.forEach(el => {
            const key = el.getAttribute('data-i18n-title');
            el.title = this.t(key);
        });
        
        // Special dynamic cases
        const statusBar = document.getElementById('statusBar');
        if (statusBar) {
            const text = statusBar.innerText;
            if (text.includes('·')) {
                const parts = text.split('·');
                statusBar.innerText = parts[0] + '· ' + this.t('chat_ready');
            }
        }
        
        const downloadText = document.getElementById('modelDownloadText');
        if (downloadText && downloadText.textContent.includes('...')) {
            downloadText.textContent = this.t('msg_downloading');
        }
    }
};

document.addEventListener('DOMContentLoaded', () => {
    window.i18n.init();
});
